import type { CacheTtlEfficiency, ModelFamily } from '@/hooks/useCacheTtl';

// Premium delta = input rate × 0.75 (1h write = 2.0×, 5m write = 1.25×).
// Current 2026-05 rates: Opus 4.5+ $5/MTok, Sonnet 4.x $3/MTok, Haiku 4.5 $1/MTok.
const PREMIUM_RATES: Record<ModelFamily, string> = {
  opus: '$3.75/MTok',
  sonnet: '$2.25/MTok',
  haiku: '$0.75/MTok',
  other: '$2.25/MTok',
};

/**
 * Build a copy/paste-ready markdown summary of cache TTL inefficiency for
 * filing a GitHub issue against Claude Code or sharing with Anthropic.
 */
export function buildShareSummary(data: CacheTtlEfficiency): string {
  const t = data.totals;
  const c = data.classification;
  const totalAnalyzed = c.usefulTokens + c.wasted5mTokens + c.staleTokens;
  const wastePct = totalAnalyzed > 0 ? (c.wasted5mTokens + c.staleTokens) / totalAnalyzed : 0;
  const usefulPct = totalAnalyzed > 0 ? c.usefulTokens / totalAnalyzed : 0;

  const fmt = (n: number) => n.toLocaleString();

  const lines = [
    `# Claude Code 1h cache TTL appears over-used`,
    ``,
    `Observed over ${data.days} days, single user, Max 20× plan.`,
    ``,
    `## Volume`,
    `- 1h cache writes:  ${fmt(t.tokens1h)} tokens (${t.writes1h.toLocaleString()} writes)`,
    `- 5m cache writes:  ${fmt(t.tokens5m)} tokens (${t.writes5m.toLocaleString()} writes)`,
    `- 1h share by tokens: ${(t.share1hByTokens * 100).toFixed(1)}%`,
    ``,
    `## 1h-write classification (strict: any cache read in same session 5–60 min after the write)`,
    `- Useful (read in 5–60 min):                   ${fmt(c.usefulTokens)} (${(usefulPct * 100).toFixed(1)}%, ${c.usefulWrites.toLocaleString()} writes)`,
    `- Wasted — only reads <5 min after:            ${fmt(c.wasted5mTokens)} (${((c.wasted5mTokens / Math.max(1, totalAnalyzed)) * 100).toFixed(1)}%, ${c.wasted5mWrites.toLocaleString()} writes)`,
    `- Stale — no cache read in 5–60 min window:    ${fmt(c.staleTokens)} (${((c.staleTokens / Math.max(1, totalAnalyzed)) * 100).toFixed(1)}%, ${c.staleWrites.toLocaleString()} writes)`,
    `- Wasted-premium share: ${(wastePct * 100).toFixed(1)}%`,
    ``,
    `## Estimated overspend (Anthropic compute, public input rates × 0.75 premium delta)`,
    ...data.cost.perModel.map(
      (m) =>
        `- ${m.model}: ${fmt(m.wastedTokens)} wasted × ${PREMIUM_RATES[m.model]} premium = $${m.premiumUsd.toFixed(2)} over ${data.days}d`,
    ),
    `- TOTAL: $${data.cost.totalPremiumUsdSampled.toFixed(2)} over ${data.days}d (~$${data.cost.totalPremiumUsdMonthly.toFixed(0)}/month at this pace, single user).`,
    ``,
    `## Methodology`,
    data.cost.methodology,
    ``,
    `Generated by claude-usage-dashboard.`,
  ];
  return lines.join('\n');
}
